DEFAULT_VIDEO_STYLE = {
    "title": {
        "top": 80,
        "width": 980,
        "height": 280,
        "font_size": 88,
        "color": "#FFD166",
        "stroke_color": "black",
        "stroke_width": 6,
        "max_length": 32,
        "line_length": 11,
    },
    "caption": {
        "top": 1390,
        "width": 980,
        "height": 320,
        "font_size": 52,
        "color": "white",
        "stroke_color": "black",
        "stroke_width": 3,
        "max_length": 56,
        "line_length": 28,
        "seconds": 4,
        "min_seconds": 1.5,
        "caption_background_enabled": False,
        "background_color": [0, 0, 0],
        "background_opacity": 0.68,
        "background_padding_x": 56,
        "background_padding_y": 24,
        "background_radius": 28,
        "background_min_width_ratio": 0.55,
        "background_max_width_ratio": 0.88,
    },
}
